[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
stof = { version = "0.8.34", features = ["basic", "tokio", "http"] }
tokio = { version = "1.47.1", features = ["full"] }
rustc-hash = "2.1.1"
bytes = "1.10.1"
